
# enter shell
shell:
	python manage.py shell

# run tests
test:
	python manage.py test polls

# show python source root
python_src:
	python -c "import django; print(django.__path__)"

# Django admin templates: django/contrib/admin/templates
